### ISSUE TITLE
Make grid more configurable, and possibly visible 

### ISSUE THREAD

**Issue by dsizzle** [HaikuArchives/ArtPaint#356] opened 2022-10-29 14:39 UTC
I'm not sure what the intended behavior of "Set grid" is but none of the values seem to do anything.  It's possible I broke it with the checker background or some other feature/fix, but it seems to do absolutely nothing at present.

**Comment by humdingerb** [comment] 2022-10-29 15:39
It still does work as intended. It activates an invisible grid that has your mouse pointer jump to the nodes. For example,set 8x8 and you can create only create rectangles that have a width/length of multiples of 8. You may want to zoom in a bit if you mislaid your specs...

Questions are
* should that grid (or at least the nodes) be made visible
* should the status bar show if the grid is active
* should it be made more configurable

In any case, I suppose you got bigger fish to fry... (not telling you to go fish. :P)

**Comment by humdingerb** [comment] 2022-11-07 14:59
Should we close this ticket, or change it to an enhancement to make the grid visible (nodes/vertices) and/or configurable (in global settings)?

**Comment by dsizzle** [comment] 2022-11-07 15:02
Yes, feel free to change it to an enhancement. That’s why I left it open.

**Comment by humdingerb** [comment] 2022-11-07 15:34
I created #384 instead, for a fresh start.

**Closed** 2022-11-07 16:01 UTC
