### ISSUE TITLE
ArtPaint crashes when viewing very high resolution images

### ISSUE THREAD

**Issue by wei2912** [HaikuArchives/ArtPaint#30] opened 2013-11-20 08:11 UTC
The following pictures were used:

http://imgsrc.hubblesite.org/hu/db/images/hs-2006-10-a-hires_jpg.jpg
- [Failure] 512 MB of RAM allocated to VM
- [Success] 1024 MB of RAM allocated to VM

http://imgsrc.hubblesite.org/hu/db/images/hs-2006-10-a-full_jpg.jpg
- [Not tested yet]

When unable to open the file, ArtPaint crashed unexpectedly instead of failing gracefully.

**Comment by dsizzle** [comment] 2023-02-05 04:55
I have not been able to reproduce this.  The image links above are stale, so I tried to find some other large images.  I opened several other large Hubble telescope images with no trouble, using a VirtualBox VM with 512MB of RAM. 

Here is a 4.2k x 2.8k image, for example:

![0big](https://user-images.githubusercontent.com/10878750/216802340-5731992d-e7ba-4707-959c-631aa3512906.png)

**Comment by dsizzle** [comment] 2023-02-05 05:52
...and here's an 8k x 6k image - it took awhile with 512MB of RAM, but didn't crash:

![0big2](https://user-images.githubusercontent.com/10878750/216804036-8efa2934-484e-4db7-95ca-b36ee6c57e1e.png)

**Comment by humdingerb** [comment] 2023-02-05 07:49
Since there isn't a debug report attached to this ticket, there's not much to go on with. Let's close the issue and have people that experience possibly size related crashes report them, if they still happen. Debug report mandatory. :)

**Comment by dsizzle** [comment] 2023-02-06 04:57
Sounds good to me, let's close this!

**Closed** 2023-02-06 18:25 UTC
Labels: bug, hacktoberfest
