### ISSUE TITLE
Add SHIFT/CTRL/OPT modifiers to selection tools

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ArtPaint#318] opened 2022-10-18 06:57 UTC
The rectangular and ellipse selection tools could use the same modifiers as the Rectangle and Ellipse drawing tools:
* SHIFT makes square/circle
* CTRL for centered

Additionally, OPT could do "Substract area", making "Add area" the default, so the "Behavior" radio buttons can be removed. Possibly holding OPT would change the cursor to include a "-".

**Comment by dsizzle** [comment] 2022-10-19 04:26
Please close #179  as a duplicate of this.

**Closed** 2022-10-24 12:06 UTC
Labels: enhancement
