### ISSUE TITLE
Cannot use Shift modifier on layer name edit field

### ISSUE THREAD

**Issue by bitigchi** [HaikuArchives/ArtPaint#655] opened 2024-02-05 19:13 UTC
Steps:

- Click on the layer name text field
- Try to input K with Shift modifier

It clashes with some other shortcut.

**Comment by humdingerb** [comment] 2024-02-06 08:08
Duplicate of #576

**Comment by korli** [comment] 2024-02-06 09:56
Indeed

**Closed by korli** 2024-02-06 09:56 UTC
